Final Project Check-in 2018-11-14
------

Group Name
-----

Aaaaaaaah

Student Names
----

1. Yihan Wang
2. Harrison Mamin
3. Wendy Xiao
4. Anush Kocharyan
5. Marwa Oussaifi

Load Data
-----

In [1]:
import pandas as pd
import numpy as np

In [2]:
crime = pd.read_csv("~/data/train.csv", parse_dates = ['Dates'])

In [3]:
# Re-label crimes that belong in the same category
crime['Category'].replace('TREA', 'TRESPASS', inplace=True)
crime['Category'].replace(['SEX OFFENSES FORCIBLE', 'SEX OFFENSES NON FORCIBLE'], 'SEX OFFENSES', inplace=True)

In [4]:
# Drop non-crimes and generic categories
drop = ["NON-CRIMINAL", "WARRANTS", "MISSING PERSON", "SUSPICIOUS OCC", "OTHER OFFENSES"]
crime = crime[~crime['Category'].isin(drop)]

In [5]:
# Sizes for the 32 classes
crime.groupby(crime['Category']).size()

Category
ARSON                            1513
ASSAULT                         76876
BAD CHECKS                        406
BRIBERY                           289
BURGLARY                        36755
DISORDERLY CONDUCT               4320
DRIVING UNDER THE INFLUENCE      2268
DRUG/NARCOTIC                   53971
DRUNKENNESS                      4280
EMBEZZLEMENT                     1166
EXTORTION                         256
FAMILY OFFENSES                   491
FORGERY/COUNTERFEITING          10609
FRAUD                           16679
GAMBLING                          146
KIDNAPPING                       2341
LARCENY/THEFT                  174900
LIQUOR LAWS                      1903
LOITERING                        1225
PORNOGRAPHY/OBSCENE MAT            22
PROSTITUTION                     7484
RECOVERED VEHICLE                3138
ROBBERY                         23000
RUNAWAY                          1946
SECONDARY CODES                  9985
SEX OFFENSES                     4536
STO

In [6]:
dow = pd.get_dummies(crime['DayOfWeek'])
district = pd.get_dummies(crime['PdDistrict'])

X = pd.concat((dow, district), axis=1)
y = crime['Category']

Fit scikit-learn model
----

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                    random_state=42)

In [9]:
clf_tree = DecisionTreeClassifier()
clf_tree = clf_tree.fit(X_train, y_train)
y_predicted = clf_tree.predict(X_test)

Evaluation Metric
----

In [11]:
confusion_matrix(y_test, y_predicted)

array([[   0,   48,    0, ...,    0,    0,    0],
       [   0, 1098,    0, ...,    0,    0,    0],
       [   0,    4,    0, ...,    0,    0,    0],
       ...,
       [   0,  548,    0, ...,    0,    0,    0],
       [   0,  864,    0, ...,    0,    0,    0],
       [   0,  178,    0, ...,    0,    0,    0]])

In [12]:
precision_score(y_test, y_predicted, average=None)

/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([0.        , 0.19032761, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.35671582, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.33092478, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [13]:
recall_score(y_test, y_predicted, average=None)

array([0.        , 0.07151697, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.33206567, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.91145982, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])