Final Project Check-in 2018-11-14
------

Group Name
-----

Aaaaaaaah

Student Names
----

1. Yihan Wang
2. Harrison Mamin
3. Wendy Xiao
4. Anush Kocharyan
5. Marwa Oussaifi

Load Data
-----

In [64]:
import pandas as pd
import numpy as np

In [65]:
crime = pd.read_csv("~/data/train.csv", parse_dates = ['Dates'])

In [66]:
# Re-label crimes that belong in the same category
crime['Category'].replace('TREA', 'TRESPASS', inplace=True)

In [67]:
# Drop non-crimes and generic categories
drop = ["NON-CRIMINAL", "WARRANTS", "MISSING PERSON", "SUSPICIOUS OCC", "SUICIDE", "RECOVERED VEHICLE", "OTHER OFFENSES"]
crime = crime[~crime['Category'].isin(drop)]

In [77]:
# Class sizes
crime.groupby(crime['Category']).size()

Category
ARSON                            1513
ASSAULT                         76876
BAD CHECKS                        406
BRIBERY                           289
BURGLARY                        36755
DISORDERLY CONDUCT               4320
DRIVING UNDER THE INFLUENCE      2268
DRUG/NARCOTIC                   53971
DRUNKENNESS                      4280
EMBEZZLEMENT                     1166
EXTORTION                         256
FAMILY OFFENSES                   491
FORGERY/COUNTERFEITING          10609
FRAUD                           16679
GAMBLING                          146
KIDNAPPING                       2341
LARCENY/THEFT                  174900
LIQUOR LAWS                      1903
LOITERING                        1225
PORNOGRAPHY/OBSCENE MAT            22
PROSTITUTION                     7484
ROBBERY                         23000
RUNAWAY                          1946
SECONDARY CODES                  9985
SEX OFFENSES FORCIBLE            4388
SEX OFFENSES NON FORCIBLE         148
STO

Because there are 31 crime categories that are highly imbalanced, we will instead try to predict whether a crime is violent or not. One of our next step is to do this target engineering.

In [69]:
# Initial feature engineering
dow = pd.get_dummies(crime['DayOfWeek'])
district = pd.get_dummies(crime['PdDistrict'])

X = pd.concat((dow, district), axis=1)
y = crime['Category']

Fit scikit-learn model
----

In [70]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                    random_state=42)

In [72]:
clf_tree = DecisionTreeClassifier(criterion='entropy')
clf_tree = clf_tree.fit(X_train, y_train)
y_predicted = clf_tree.predict(X_test)

Evaluation Metric
----

In [86]:
# Labels for confusion matrix and marginal precision and recall
labels = crime['Category'].unique()

array(['LARCENY/THEFT', 'VEHICLE THEFT', 'VANDALISM', 'ROBBERY',
       'ASSAULT', 'WEAPON LAWS', 'BURGLARY', 'DRUNKENNESS',
       'FORGERY/COUNTERFEITING', 'DRUG/NARCOTIC', 'STOLEN PROPERTY',
       'SECONDARY CODES', 'TRESPASS', 'FRAUD', 'KIDNAPPING', 'RUNAWAY',
       'DRIVING UNDER THE INFLUENCE', 'SEX OFFENSES FORCIBLE',
       'PROSTITUTION', 'DISORDERLY CONDUCT', 'ARSON', 'FAMILY OFFENSES',
       'LIQUOR LAWS', 'BRIBERY', 'EMBEZZLEMENT', 'LOITERING',
       'SEX OFFENSES NON FORCIBLE', 'EXTORTION', 'GAMBLING', 'BAD CHECKS',
       'PORNOGRAPHY/OBSCENE MAT'], dtype=object)

In [87]:
confusion_matrix(y_test, y_predicted, labels=labels)

array([[31444,     0,     0,     0,  1390,     0,     0,     0,     0,
         1982,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0],
       [ 9487,     0,     0,     0,  1125,     0,     0,     0,     0,
          213,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0],
       [ 7769,     0,     0,     0,   773,     0,     0,     0,     0,
          331,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0],
       [ 3754,     0,     0,     0,   392,     0,     0,     0,     0,
          416,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0],


In [88]:
precision_score(y_test, y_predicted, labels=labels, average=None)

/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([0.33401317, 0.        , 0.        , 0.        , 0.19464112,
       0.        , 0.        , 0.        , 0.        , 0.35797116,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

In [89]:
recall_score(y_test, y_predicted, labels=labels, average=None)

array([0.90314798, 0.        , 0.        , 0.        , 0.08988908,
       0.        , 0.        , 0.        , 0.        , 0.32685756,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])